version: 2

models:
  - name: fct_current_hourly
    description: >
      Table for the Visualisation tool to pick up from data from for the current air quality data 
      comprising of concentrations in (µg/m³) of different pollutants for a particular location.
      Excludes temperature and humidity readings.
    tests:
     - dbt_utils.unique_combination_of_columns:
        combination_of_columns:
          - location_id
          - dateandtime
          - sensor_id
        severity: error

  - name: sensor_name
    description: Name of the pollutant being measured (e.g., CO, NO2)
    tests:
      - accepted_values:
          values: ['CO', 'NO', 'NO2', 'SO2', 'O3', 'PM2.5', 'PM25', 'PM10'] # PM2.5 is coming as PM25 sometimes from source
          severity: warn
  

  - name: dim_cumulative_hourly
    description: >
      Cumulative records of raw hourly measurements. Used for 
      longitudinal accumulation of hourly data. and downstream processing.
    columns:
      - name: unique_record_id
        description: MD5 hash of location_id+dateandtime+sensor_id
        tests:
          - not_null
          - unique:
              severity: error  # if duplicates somehow appear

      - name: sensor_name
        tests:
          - accepted_values:
              values: ['CO', 'NO', 'NO2', 'SO2', 'O3', 'PM2.5', 'PM25', 'PM10'] # PM2.5 is coming as PM25 sometimes from source

  - name: dim_whole_data
    description: Unified view of historical and cumulative air quality data
    columns:
      - name: unique_record_id
        tests:
          - not_null
          - unique:
              severity: error  # if duplicates somehow appear
      - name: sensor_name
        tests:
          - accepted_values:
             values: ['CO', 'NO', 'NO2', 'SO2', 'O3', 'PM2.5', 'PM25', 'PM10'] # PM2.5 is coming as PM25 sometimes from source


  - name: fct_aqi_data
    description: Calculated AQI values per location-day
    columns:
     - name: dominant_pollutant
       tests:
        - not_null
        - accepted_values:
            values: [ 'PM2.5', 'PM25', 'PM10', 'NO2', 'SO2']
     - name: air_quality
       tests:
        - accepted_values:
            values: ['Good', 'Satisfactory', 'Moderate', 'Poor', 'Very Poor', 'Severe', 'EMPTY']


  - name: fct_temporal_locationwise
    description: "Daily pollutant concentration per sensor and location"
    columns:
      - name: unique_record_id
        tests:
          - unique:
             severity: error  # if duplicates somehow appear
          - not_null
