api_secret_key = "74eb7d5de7502c9b343c1f6144affdfd826dae6"
location_list = "[3409411, 3409391, 3409390, 3409360, 3409375, 3409376, 363601, 42240, 10903]"  # OpenAQ location ids for my region under consideration
base_url = "https://api.openaq.org/v3/"

[destination.filesystem]
bucket_url = "gs://air-quality-assam-bucket"  #you can name your own bucket as desired
merge_job = true

[destination.filesystem.credentials]
project_id = "dez-capstone-project1" # this is my project id
private_key ="-----BEGIN PRIVATE KEY---YOUR KEY--\n-----END PRIVATE KEY-----\n" # please use your service account private key!
client_email = "cap-proj1-svc-acct@dez-capstone-project1.iam.gserviceaccount.com" # this is my service account email (Principal)

